[package]
name = "backend"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
anyhow = "1.0.97"
async-trait = "0.1.87"
bcs = "0.1"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "5f2c63266a065996d53f98156f0412782b468597", package = "fastcrypto" }
iota = { git = "https://github.com/iotaledger/iota.git", package = "iota", version = "0.10.0-alpha" }
iota-keys = { git = "https://github.com/iotaledger/iota.git", package = "iota-keys", version = "0.10.0-alpha" }
iota-sdk = { git = "https://github.com/iotaledger/iota.git", package = "iota-sdk", version = "0.10.0-alpha" }
iota-config = { git = "https://github.com/iotaledger/iota.git", package = 'iota-config', version = "0.10.0-alpha" }
iota-json-rpc-types = { git = "https://github.com/iotaledger/iota.git", package = 'iota-json-rpc-types', version = "0.10.0-alpha" }
jsonpath-rust = "0.7"
move_core_types = { git = "https://github.com/iotaledger/iota.git", package = "move-core-types" }
secret-storage = { git = "https://github.com/iotaledger/secret-storage", rev = "74f2092f83f6d19bd399913ef021bedca722ef66" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shared-crypto = { git = "https://github.com/iotaledger/iota.git", package = "shared-crypto", version = "0.10.0-alpha" }
tokio = { version = "1.43.0", features = ["full"] }
ith = { path = "./ith/ith.rs/ith" }
dotenvy = "0.15.7"
axum = "0.8.1"


[lib]
path = "src/lib/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "init_ith"
path = "src/scripts/init_ith.rs"

[[bin]]
name = "init_accounts"
path = "src/scripts/init_accounts.rs"

[[bin]]
name = "import_accounts"
path = "src/scripts/import_accounts.rs"

[[bin]]
name = "faucet"
path = "src/scripts/faucet.rs"
