[package]
name = "IOTA Custom Notarization"
license = "Apache-2.0"
version = "0.1.0"
edition = "2024.beta"


[dependencies]
Hierarchies = { git = "https://github.com/iotaledger/hierarchies.git", subdir = "hierarchies-move", rev = "v0.1.2" }

[addresses]
custom_notarization = "0x0"
